### ISSUE TITLE
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator)) on Mac OS runner

### ISSUE THREAD

**Issue by kwin** [ScaCap/action-surefire-report#95]
The default Mac OS runner does no longer seem to be compatible with this action. It emits

```
Run scacap/action-surefire-report@v1
  with:
    check_name: Test report (macOS-latest, JDK 8)
    github_token: ***
    report_paths: **/surefire-reports/TEST-*.xml, **/failsafe-reports/TEST-*.xml
    fail_on_test_failures: false
    fail_if_no_tests: true
    skip_publishing: false
  env:
    JAVA_HOME: /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.345-1/x64/Contents/Home
    MVN_ADDITIONAL_OPTS: 
    MVN_GOAL: clean verify
/Users/runner/work/_actions/scacap/action-surefire-report/v1/dist/index.js:15798
    throw error;
    ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (/Users/runner/work/_actions/scacap/action-surefire-report/v1/dist/index.js:[2](https://github.com/Adobe-Consulting-Services/acs-aem-commons/actions/runs/3385000713/jobs/5622637838#step:6:2)98[3](https://github.com/Adobe-Consulting-Services/acs-aem-commons/actions/runs/3385000713/jobs/5622637838#step:6:3)3:26)
    at osName (/Users/runner/work/_actions/scacap/action-surefire-report/v1/dist/index.js:7110:18)
    at getUserAgent (/Users/runner/work/_actions/scacap/action-surefire-report/v1/dist/index.js:15792:53)
    at parseOptions (/Users/runner/work/_actions/scacap/action-surefire-report/v1/dist/index.js:793[4](https://github.com/Adobe-Consulting-Services/acs-aem-commons/actions/runs/3385000713/jobs/5622637838#step:6:4):[5](https://github.com/Adobe-Consulting-Services/acs-aem-commons/actions/runs/3385000713/jobs/5622637838#step:6:5)7)
    at new Octokit (/Users/runner/work/_actions/scacap/action-surefire-report/v1/dist/index.js:7[6](https://github.com/Adobe-Consulting-Services/acs-aem-commons/actions/runs/3385000713/jobs/5622637838#step:6:6)24:31)
    at Object.858 (/Users/runner/work/_actions/scacap/action-surefire-report/v1/dist/index.js:15253:28)
    at __webpack_require__ (/Users/runner/work/_actions/scacap/action-surefire-report/v1/dist/index.js:24:31)
    at Object.8[7](https://github.com/Adobe-Consulting-Services/acs-aem-commons/actions/runs/3385000713/jobs/5622637838#step:6:7)2 (/Users/runner/work/_actions/scacap/action-surefire-report/v1/dist/index.js:1544[8](https://github.com/Adobe-Consulting-Services/acs-aem-commons/actions/runs/3385000713/jobs/5622637838#step:6:8):16)
    at __webpack_require__ (/Users/runner/work/_actions/scacap/action-surefire-report/v1/dist/index.js:24:31)
    at Object.507 (/Users/runner/work/_actions/scacap/action-surefire-report/v1/dist/index.js:7[9](https://github.com/Adobe-Consulting-Services/acs-aem-commons/actions/runs/3385000713/jobs/5622637838#step:6:9)70:[16](https://github.com/Adobe-Consulting-Services/acs-aem-commons/actions/runs/3385000713/jobs/5622637838#step:6:17))
```

The runners for other operating systems are not affected. Probably related to #85.

**Comment by ghaiszaher** [comment]
Please raise an issue in https://github.com/ScalableCapital/action-surefire-report if the issue persists
